export const doctorsList = [
    // --- قسم أطباء الأسنان ---
    {
        id: 1,
        name: "د. مؤمن عدي",
        category: "dentist",
        specialty: "طب وجراحة الفم والأسنان",
        degree: "طالب طب أسنان - جامعة تكريت (المرحلة الثالثة)",
        university: "جامعة تكريت",
        experience: "العيادات التعليمية",
        rating: "5.0",
        thanksCount: 450,
        landmark: "سامراء - حي المعلمين",
        tip: "صحة أسنانك تبدأ من تفريشها ليلاً قبل النوم، فهي الفترة الأطول التي تنشط فيها البكتيريا.",
        logo: "https://cdn-icons-png.flaticon.com/512/3481/3481061.png",
        images: [
            "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?q=80&w=800",
            "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?q=80&w=800"
        ],
        phone: "07701234567",
        whatsapp: "07701234567",
        workingDays: "الأحد إلى الخميس",
        workingHours: "8:00 صباحاً - 2:00 ظهراً",
        hospitalShift: "الاستشارية التعليمية - كلية طب الأسنان",
        isFree: true,
        specialOffer: "حشوات وتنظيف مجاني بإشراف أساتذة الكلية لخدمة أهلنا."
    },
    {
        id: 2,
        name: "د. عمر طارق",
        category: "dentist",
        specialty: "زراعة وتجميل الأسنان",
        degree: "بورد (دكتوراه) جراحة الوجه والفكين",
        university: "جامعة بغداد",
        experience: "12 سنة",
        rating: "4.8",
        thanksCount: 890,
        landmark: "سامراء - شارع الأطباء الرئيسي",
        tip: "المضمضة بالماء والملح الدافئ مرتين أسبوعياً تقي من التهابات اللثة.",
        logo: "https://cdn-icons-png.flaticon.com/512/3481/3481061.png",
        images: [
            "https://images.unsplash.com/photo-1629909613654-28e377c37b09?q=80&w=800"
        ],
        phone: "07810000000",
        whatsapp: "07810000000",
        workingDays: "السبت إلى الأربعاء",
        workingHours: "4:00 عصراً - 9:00 مساءً",
        isFree: false,
        specialOffer: "خصم 20% على ابتسامة هوليود هذا الشهر."
    },
    {
        id: 3,
        name: "د. رقية سعد",
        category: "dentist",
        specialty: "طب أسنان الأطفال وتقويم الأسنان",
        degree: "ماجستير تقويم الأسنان",
        university: "جامعة الموصل",
        experience: "8 سنوات",
        rating: "4.9",
        thanksCount: 620,
        landmark: "سامراء - حي الضباط",
        tip: "يجب زيارة طبيب الأسنان للأطفال عند ظهور أول سن لبني.",
        logo: "https://cdn-icons-png.flaticon.com/512/3481/3481061.png",
        images: [
            "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=800",
            "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?q=80&w=800"
        ],
        phone: "07720000000",
        whatsapp: "07720000000",
        workingDays: "السبت، الإثنين، الأربعاء",
        workingHours: "3:00 عصراً - 7:00 مساءً",
        isFree: false
    },
    {
        id: 4,
        name: "د. هدى إبراهيم",
        category: "dentist",
        specialty: "حشوات الجذور والعلاج التحفظي",
        degree: "بكالوريوس طب وجراحة الفم والأسنان",
        university: "جامعة الانبار",
        experience: "5 سنوات",
        rating: "4.6",
        thanksCount: 310,
        landmark: "سامراء - حي الجبير",
        tip: "تجنب كسر الأشياء الصلبة بأسنانك للحفاظ على مينا السن.",
        logo: "https://cdn-icons-png.flaticon.com/512/3481/3481061.png",
        images: [
            "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?q=80&w=800"
        ],
        phone: "07830000000",
        whatsapp: "07830000000",
        workingDays: "السبت إلى الخميس",
        workingHours: "4:00 عصراً - 8:00 مساءً",
        hospitalShift: "مركز صحي الجبير",
        isFree: false
    },
    {
        id: 5,
        name: "د. عبد الله السامرائي",
        category: "dentist",
        specialty: "طب أسنان عام",
        degree: "بكالوريوس طب أسنان",
        university: "جامعة تكريت",
        experience: "سنتان",
        rating: "4.7",
        thanksCount: 150,
        landmark: "سامراء - القلعة",
        tip: "تغيير فرشاة الأسنان كل 3 أشهر أمر ضروري جداً.",
        logo: "https://cdn-icons-png.flaticon.com/512/3481/3481061.png",
        images: [
            "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?q=80&w=800"
        ],
        phone: "07740000000",
        whatsapp: "07740000000",
        workingDays: "يومياً عدا الجمعة",
        workingHours: "5:00 عصراً - 9:00 مساءً",
        isFree: true,
        specialOffer: "قلع الأسنان البسيط مجاناً لكبار السن يوم الخميس."
    },

    // --- قسم الأطباء (بشري) ---
    {
        id: 6,
        name: "د. محمد أياد",
        category: "doctor",
        specialty: "أخصائي أمراض القلب والباطنية",
        degree: "البورد العربي",
        university: "جامعة بغداد",
        experience: "15 سنة",
        rating: "4.9",
        thanksCount: 1200,
        landmark: "سامراء - شارع الأطباء",
        tip: "ممارسة المشي لنصف ساعة يومياً تقي من تصلب الشرايين.",
        logo: "https://cdn-icons-png.flaticon.com/512/3004/3004416.png",
        images: [
            "https://images.unsplash.com/photo-1551076805-e18690c5e561?q=80&w=800"
        ],
        phone: "07850000000",
        whatsapp: "07850000000",
        workingDays: "السبت إلى الأربعاء",
        workingHours: "4:00 عصراً - 8:00 مساءً",
        hospitalShift: "مستشفى سامراء العام - الباطنية",
        isFree: false
    },
    {
        id: 7,
        name: "د. أحمد السامرائي",
        category: "doctor",
        specialty: "أخصائي طب الأطفال وحديثي الولادة",
        degree: "دبلوم عالي طب الأطفال",
        university: "جامعة المستنصرية",
        experience: "10 سنوات",
        rating: "4.8",
        thanksCount: 950,
        landmark: "سامراء - حي المعلمين",
        tip: "الرضاعة الطبيعية في الأشهر الستة الأولى تقوي مناعة طفلك مدى الحياة.",
        logo: "https://cdn-icons-png.flaticon.com/512/3004/3004416.png",
        images: [
            "https://images.unsplash.com/photo-1630080313838-8e658933e8b0?q=80&w=800"
        ],
        phone: "07760000000",
        whatsapp: "07760000000",
        workingDays: "السبت إلى الخميس",
        workingHours: "3:00 عصراً - 8:00 مساءً",
        isFree: false,
        specialOffer: "كشفية مجانية للأيتام كل يوم جمعة صباحاً."
    },
    {
        id: 8,
        name: "د. سارة علي",
        category: "doctor",
        specialty: "أخصائية النسائية والتوليد والعقم",
        degree: "البورد العراقي",
        university: "جامعة الكوفة",
        experience: "14 سنة",
        rating: "5.0",
        thanksCount: 1500,
        landmark: "سامراء - حي الخضراء",
        tip: "تناول حمض الفوليك قبل الحمل بشهر يقي الجنين من التشوهات.",
        logo: "https://cdn-icons-png.flaticon.com/512/3004/3004416.png",
        images: [
            "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=800"
        ],
        phone: "07870000000",
        whatsapp: "07870000000",
        workingDays: "يومياً عدا الجمعة والأحد",
        workingHours: "4:00 عصراً - 9:00 مساءً",
        hospitalShift: "مستشفى سامراء العام - صالة الولادة",
        isFree: false
    },
    {
        id: 9,
        name: "د. علي محمود",
        category: "doctor",
        specialty: "أخصائي جراحة العظام والكسور",
        degree: "زميل كلية الجراحين الملكية",
        university: "لندن",
        experience: "20 سنة",
        rating: "4.9",
        thanksCount: 2100,
        landmark: "سامراء - شارع البنك",
        tip: "الجلوس الصحيح أمام الحاسوب يجنبك الانزلاق الغضروفي المبكر.",
        logo: "https://cdn-icons-png.flaticon.com/512/3004/3004416.png",
        images: [
            "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=800"
        ],
        phone: "07780000000",
        whatsapp: "07780000000",
        workingDays: "السبت، الإثنين، الخميس",
        workingHours: "5:00 عصراً - 10:00 مساءً",
        isFree: false
    },
    {
        id: 10,
        name: "د. زينب عباس",
        category: "doctor",
        specialty: "أخصائية طب وجراحة العيون",
        degree: "البورد العربي",
        university: "جامعة بغداد",
        experience: "11 سنة",
        rating: "4.7",
        thanksCount: 840,
        landmark: "سامراء - حي الشرطة",
        tip: "قاعدة 20-20-20: كل 20 دقيقة انظر لشيء يبعد 20 قدماً لمدة 20 ثانية.",
        logo: "https://cdn-icons-png.flaticon.com/512/3004/3004416.png",
        images: [
            "https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=800"
        ],
        phone: "07890000000",
        whatsapp: "07890000000",
        workingDays: "السبت إلى الأربعاء",
        workingHours: "4:00 عصراً - 8:00 مساءً",
        isFree: false
    },
    {
        id: 11,
        name: "د. قاسم الحسن",
        category: "doctor",
        specialty: "الجراحة العامة والناظورية",
        degree: "بورد جراحة عامة",
        university: "جامعة البصرة",
        experience: "18 سنة",
        rating: "4.8",
        thanksCount: 1120,
        landmark: "سامراء - شارع الأطباء",
        tip: "لا تتجاهل آلام البطن المفاجئة والحادة، فقد تكون علامة لالتهاب الزائدة.",
        logo: "https://cdn-icons-png.flaticon.com/512/3004/3004416.png",
        images: [
            "https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=800"
        ],
        phone: "07790000000",
        whatsapp: "07790000000",
        workingDays: "الأحد إلى الخميس",
        workingHours: "5:00 عصراً - 9:00 مساءً",
        hospitalShift: "مستشفى سامراء العام - صالة العمليات",
        isFree: false
    },
    {
        id: 12,
        name: "د. مصطفى كريم",
        category: "doctor",
        specialty: "أخصائي الجملة العصبية والدماغ",
        degree: "بورد عراقي",
        university: "جامعة بغداد",
        experience: "9 سنوات",
        rating: "4.6",
        thanksCount: 430,
        landmark: "سامراء - حي الضباط",
        tip: "الصداع المستمر الذي يوقظك من النوم يحتاج لتقييم طبي فوري.",
        logo: "https://cdn-icons-png.flaticon.com/512/3004/3004416.png",
        images: [
            "https://images.unsplash.com/photo-1551076805-e18690c5e561?q=80&w=800"
        ],
        phone: "07801111111",
        whatsapp: "07801111111",
        workingDays: "السبت، الأحد، الثلاثاء",
        workingHours: "4:00 عصراً - 8:00 مساءً",
        isFree: false
    },
    {
        id: 13,
        name: "د. ياسين طه",
        category: "doctor",
        specialty: "أخصائي الأنف والأذن والحنجرة",
        degree: "دبلوم عالي",
        university: "جامعة الموصل",
        experience: "13 سنة",
        rating: "4.5",
        thanksCount: 560,
        landmark: "سامراء - حي الجبير",
        tip: "استخدام أعواد القطن لتنظيف الأذن يدفع الشمع للداخل ويسبب الانسداد.",
        logo: "https://cdn-icons-png.flaticon.com/512/3004/3004416.png",
        images: [
            "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=800"
        ],
        phone: "07702222222",
        whatsapp: "07702222222",
        workingDays: "السبت إلى الأربعاء",
        workingHours: "4:00 عصراً - 7:00 مساءً",
        isFree: true,
        specialOffer: "غسل الأذن مجاناً لذوي الدخل المحدود كل يوم اثنين."
    },

    // --- قسم الصيدليات ---
    {
        id: 14,
        name: "صيدلية الرازي",
        category: "pharmacy",
        specialty: "توفير كافة الأدوية والمستلزمات الطبية",
        degree: "بإدارة: ص. حارث محمد",
        university: "جامعة تكريت",
        experience: "صيدلية معتمدة",
        rating: "4.9",
        thanksCount: 3400,
        landmark: "سامراء - شارع الأطباء",
        tip: "تأكد دائماً من تاريخ صلاحية الدواء قبل استخدامه.",
        logo: "https://cdn-icons-png.flaticon.com/512/4320/4320337.png",
        images: [
            "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=800"
        ],
        phone: "07803333333",
        whatsapp: "07803333333",
        workingDays: "طيلة أيام الأسبوع",
        workingHours: "8:00 صباحاً - 12:00 ليلاً",
        isFree: false
    },
    {
        id: 15,
        name: "صيدلية الشفاء الخافر",
        category: "pharmacy",
        specialty: "أدوية الأمراض المزمنة ومستحضرات التجميل",
        degree: "بإدارة: ص. شهد عبد الله",
        university: "جامعة بغداد",
        experience: "صيدلية خافرة",
        rating: "5.0",
        thanksCount: 5200,
        landmark: "سامراء - حي المعلمين",
        tip: "احتفظ بالأدوية في مكان بارد وجاف بعيداً عن متناول الأطفال.",
        logo: "https://cdn-icons-png.flaticon.com/512/4320/4320337.png",
        images: [
            "https://images.unsplash.com/photo-1576602976047-174e57a47881?q=80&w=800"
        ],
        phone: "07704444444",
        whatsapp: "07704444444",
        workingDays: "طيلة أيام الأسبوع",
        workingHours: "مفتوح 24 ساعة",
        isFree: false,
        specialOffer: "قياس الضغط والسكر مجاناً للجميع."
    },
    {
        id: 16,
        name: "صيدلية ابن سينا",
        category: "pharmacy",
        specialty: "أدوية، مكملات غذائية، عناية بالبشرة",
        degree: "بإدارة: ص. مصطفى خالد",
        university: "جامعة الموصل",
        experience: "صيدلية معتمدة",
        rating: "4.8",
        thanksCount: 1800,
        landmark: "سامراء - حي الخضراء",
        tip: "لا توقف المضاد الحيوي بمجرد الشعور بالتحسن، أكمل الجرعة بالكامل.",
        logo: "https://cdn-icons-png.flaticon.com/512/4320/4320337.png",
        images: [
            "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?q=80&w=800"
        ],
        phone: "07805555555",
        whatsapp: "07805555555",
        workingDays: "السبت إلى الخميس",
        workingHours: "9:00 صباحاً - 11:00 مساءً",
        isFree: false
    },
    {
        id: 17,
        name: "صيدلية الأمل",
        category: "pharmacy",
        specialty: "أدوية عامة وعلاجات جلدية",
        degree: "بإدارة: ص. نور حسن",
        university: "جامعة تكريت",
        experience: "صيدلية معتمدة",
        rating: "4.7",
        thanksCount: 900,
        landmark: "سامراء - القلعة",
        tip: "يفضل تناول الفيتامينات الصباحية بعد الإفطار لامتصاص أفضل.",
        logo: "https://cdn-icons-png.flaticon.com/512/4320/4320337.png",
        images: [
            "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=800"
        ],
        phone: "07706666666",
        whatsapp: "07706666666",
        workingDays: "السبت إلى الخميس",
        workingHours: "4:00 عصراً - 10:00 مساءً",
        isFree: false
    },

    // --- قسم المختبرات ---
    {
        id: 18,
        name: "مختبر البيان التخصصي",
        category: "lab",
        specialty: "تحليلات مرضية متقدمة وفحوصات هرمونية",
        degree: "بإدارة: د. محمود شاكر",
        university: "جامعة بغداد",
        experience: "أجهزة ألمانية حديثة",
        rating: "4.9",
        thanksCount: 2200,
        landmark: "سامراء - شارع الأطباء",
        tip: "تحليل السكر التراكمي الدقيق يتطلب صياماً من 8 إلى 10 ساعات.",
        logo: "https://cdn-icons-png.flaticon.com/512/1046/1046274.png",
        images: [
            "https://images.unsplash.com/photo-1579154204601-01588f351e67?q=80&w=800",
            "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?q=80&w=800"
        ],
        phone: "07807777777",
        whatsapp: "07807777777",
        workingDays: "السبت إلى الخميس",
        workingHours: "8:00 صباحاً - 8:00 مساءً",
        isFree: false,
        specialOffer: "خصم 20% على الفحص الشامل نهاية كل شهر."
    },
    {
        id: 19,
        name: "مختبر النور للتحليلات",
        category: "lab",
        specialty: "فحوصات الدم والفايروسات والكيمياء السريرية",
        degree: "بإدارة: د. إبراهيم خليل",
        university: "جامعة تكريت",
        experience: "دقة وسرعة في الإنجاز",
        rating: "4.8",
        thanksCount: 1600,
        landmark: "سامراء - حي الجبير",
        tip: "شرب الماء بكثرة قبل سحب الدم يسهل العملية ويمنع الجفاف.",
        logo: "https://cdn-icons-png.flaticon.com/512/1046/1046274.png",
        images: [
            "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?q=80&w=800"
        ],
        phone: "07708888888",
        whatsapp: "07708888888",
        workingDays: "السبت إلى الخميس",
        workingHours: "7:30 صباحاً - 9:00 مساءً",
        isFree: true,
        specialOffer: "تحليل فصيلة الدم مجاناً لطلبة المدارس."
    },
    {
        id: 20,
        name: "مختبر الحياة",
        category: "lab",
        specialty: "تحليلات مرضية وفحوصات الزواج",
        degree: "بإدارة: د. لمياء جاسم",
        university: "جامعة المستنصرية",
        experience: "مختبر معتمد للتقارير الرسمية",
        rating: "4.7",
        thanksCount: 1100,
        landmark: "سامراء - حي المعتصم",
        tip: "بعض تحليلات الدهون تتطلب الامتناع عن أكل اللحوم الدسمة قبلها بيوم.",
        logo: "https://cdn-icons-png.flaticon.com/512/1046/1046274.png",
        images: [
            "https://images.unsplash.com/photo-1579154204601-01588f351e67?q=80&w=800"
        ],
        phone: "07809999999",
        whatsapp: "07809999999",
        workingDays: "السبت إلى الخميس",
        workingHours: "8:00 صباحاً - 2:00 ظهراً | 4:00 عصراً - 8:00 مساءً",
        isFree: false
    }
];